version: "3.8"

services:
  postgres:
    image: postgres:17.2
    container_name: bsuir-postgres-compose
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${BACKUP_DIR}:/backups
      - /Users/ivannikolayeu/Documents/bsuir-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
