postgres:
  host: "localhost"
  port: 5432
  database: "temp"
  username: "postgres"
  password: "123"
  connectionAttempts: 5
  delayBtwAttempts: "10s"
  queryTimeout: "5s"

appServer:
  host: "localhost"
  port: 8080
  readTimeout: "10s"
  writeTimeout: "10s"

app:
  logLevel: "debug"
  shutdownTimeout: "10s"
  backupDir: "/Users/ivannikolayeu/bsuir/db/lab6/backend/backup"