basePath: /
definitions:
  domain.Backup:
    properties:
      created_at:
        type: string
      filename:
        type: string
      size:
        type: integer
    type: object
  domain.BackupCreated:
    properties:
      filename:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  domain.BackupDeleted:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
  rest.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  rest.ExecuteRequest:
    properties:
      query:
        type: string
    type: object
  rest.TableResponse:
    properties:
      tables:
        items:
          type: string
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для работы с базой данных
  title: Database API
  version: "1.0"
paths:
  /backup/create:
    post:
      consumes:
      - application/json
      description: Creates a new backup of the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/domain.BackupCreated'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Create new backup
      tags:
      - backup
  /backup/delete/{filename}:
    delete:
      consumes:
      - application/json
      description: Deletes a specific backup file
      parameters:
      - description: Backup filename
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.BackupDeleted'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Delete backup
      tags:
      - backup
  /backup/download/{filename}:
    get:
      consumes:
      - application/json
      description: Downloads a specific backup file
      parameters:
      - description: Backup filename
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/sql
      responses:
        "200":
          description: OK
          schema:
            type: file
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Download backup
      tags:
      - backup
  /backup/list:
    get:
      consumes:
      - application/json
      description: Returns a list of all available backups
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              items:
                $ref: '#/definitions/domain.Backup'
              type: array
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Get list of backups
      tags:
      - backup
  /backup/restore/{filename}:
    post:
      consumes:
      - application/json
      description: Restores the database from a specific backup
      parameters:
      - description: Backup filename
        in: path
        name: filename
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.BackupCreated'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Restore backup
      tags:
      - backup
  /execute:
    post:
      consumes:
      - application/json
      description: Executes an arbitrary SQL query and returns the result
      parameters:
      - description: SQL query
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/rest.ExecuteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Execute SQL query
      tags:
      - execute
  /tables:
    get:
      consumes:
      - application/json
      description: Returns a list of all tables in the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.TableResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Get list of tables
      tags:
      - tables
  /tables/delete/all:
    delete:
      consumes:
      - application/json
      description: Deletes all tables from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.ErrorResponse'
      summary: Delete all tables
      tags:
      - tables
swagger: "2.0"
